package com.wj.hsqldb.db;

import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.AnnotationConfigApplicationContext;
import org.springframework.context.annotation.ComponentScan;
import org.springframework.context.annotation.Configuration;

import java.awt.*;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

/**
 * Created by wenjing.liu on 2021/3/12 in J1.
 */
@Configuration
@ComponentScan
public class LibrarianDbTest {
    public static void main(String[] args) {
        ApplicationContext context = new AnnotationConfigApplicationContext(LibrarianDbTest.class);
        JdbcConfiguration configuration = context.getBean(JdbcConfiguration.class);
        Statement statement = configuration.createStatement();
        createLibrarianBook(statement);
        query(statement);
    }

    private static void createLibrarianBook(Statement statement) {
        String create = String.format("CREATE TABLE IF NOT EXISTS %s (id INTEGER GENERATED BY DEFAULT AS IDENTITY," +
                "name varchar(20) not NULL, age INTEGER , sex varchar(2)," +
                "PRIMARY KEY (id))", "librarian");
        try {
            boolean result = statement.execute(create);
            System.out.println("result = " + result);
        } catch (SQLException throwables) {
            throwables.printStackTrace();
        }
    }


    private static void query(Statement statement) {
        String sql = "select * from librarian";
        try {
            ResultSet set = statement.executeQuery(sql);
            while (set.next()) {

            }
        } catch (SQLException throwables) {
            throwables.printStackTrace();
        }
    }
}
