package com.wj.hsqldb.service;

import com.wj.hsqldb.model.Librarian;
import org.hibernate.Criteria;
import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.springframework.stereotype.Component;

import javax.annotation.PostConstruct;
import javax.annotation.Resource;
import java.util.List;

/**
 * Created by wenjing.liu on 2021/3/11 in J1.
 */
//@Component
public class LibrarianManagerService {
    private String tableName = "librarian";
    //@Resource
    private SessionFactory sessionFactory;

    private Session getSession() {
        return sessionFactory.getCurrentSession();
    }

    //@PostConstruct
    public void createTable() {
        //getSession().
    }

    public void insertLibrarian(Librarian librarian) {
        getSession().update(librarian);
    }

    public List<Librarian> getLibrarian() {
        // String sql = String.format("SELECT * FROM %s", tableName);
        // SQLQuery<Librarian> query = getSession().createSQLQuery(sql);
        //return query.list();
        //load()是首先访问缓存,如果没有则访问数据库,get()是直接访问数据库!
        Criteria criteria = getSession().createCriteria(Librarian.class);
        return criteria.list();

    }

    String create = String.format("CREATE TABLE %s (id INTEGER GENERATED BY DEFAULT AS IDENTITY," +
            "name varchar(20) not NULL, age INTEGER , sex varchar(2)," +
            "PRIMARY KEY (id))", tableName);
}
